# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0003_auto_20170511_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
