# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0004_auto_20170511_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
